name: team_manage_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.5.3
  file_picker: ^10.1.2
  image_picker: ^1.0.2
  path: ^1.8.0
  mime: ^1.0.4
  intl: ^0.18.1
  url_launcher: ^6.1.10
  dio: ^5.3.2
  path_provider: ^2.0.11
  permission_handler: ^12.0.0+1
  universal_html: ^2.2.4
  file_saver: ^0.2.14
  graphview: ^1.2.0
  flutter_speed_dial: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
